CREATE TABLE BALANCE (
 USER_ID SERIAL PRIMARY KEY NOT NULL,
 CURRENT_BALANCE FLOAT
);

CREATE TABLE OPERATIONS (
 OPERATION_ID SERIAL PRIMARY KEY NOT NULL,
 USER_ID SERIAL REFERENCES BALANCE(USER_ID),
 OPERATION_TYPE VARCHAR(20),
 OPERATION_TIME DATE,
 MONEY_AMOUNT FLOAT,
 BENEFICIARY_ID INT REFERENCES BALANCE(USER_ID)
)